language: php
php:
  - '7.0'
install: composer install --prefer-dist
script:
  - ./vendor/bin/phpstan analyse -c phpstan.neon -l 5 src
  - ./vendor/bin/phpcs src --runtime-set ignore_warnings_on_exit true --runtime-set installed_paths vendor/magento/marketplace-eqp --standard=MEQP2
cache:
  directories:
    - $HOME/.composer/cache/files
